--liquibase formatted sql

--changeset iremstech:4
CREATE TABLE WELCOME_BOARD
(
  ID UUID DEFAULT uuid_generate_v4(),
  NAME VARCHAR(100) NOT NULL,
  MESSAGE_TEMPLATE_ID UUID,
  PRIMARY KEY (ID),
  CONSTRAINT FK_WB_MT FOREIGN KEY (MESSAGE_TEMPLATE_ID) REFERENCES MESSAGE_TEMPLATE(ID)
);
--rollback DROP TABLE WELCOME_BOARD;

--changeset iremstech:5
ALTER TABLE GUEST ADD COLUMN WELCOME_BOARD_ID UUID;
ALTER TABLE GUEST ADD CONSTRAINT FK_G_WB FOREIGN KEY (WELCOME_BOARD_ID) REFERENCES WELCOME_BOARD(ID);


